language: ruby

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

rvm:
  - 2.5.3
  - ruby-head

gemfile:
  - gemfiles/rails_5.2.gemfile

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake spec
